#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pycares
Version  : 4.1.2
Release  : 13
URL      : https://files.pythonhosted.org/packages/83/61/17bd0cfb9c4dc8c3738484d604b50d47c78fe4fcfe0ca2c58a61a106f578/pycares-4.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/61/17bd0cfb9c4dc8c3738484d604b50d47c78fe4fcfe0ca2c58a61a106f578/pycares-4.1.2.tar.gz
Summary  : Python interface for c-ares
Group    : Development/Tools
License  : MIT
Requires: pycares-license = %{version}-%{release}
Requires: pycares-python = %{version}-%{release}
Requires: pycares-python3 = %{version}-%{release}
Requires: cffi
Requires: idna
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : idna
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
===========================

%package license
Summary: license components for the pycares package.
Group: Default

%description license
license components for the pycares package.


%package python
Summary: python components for the pycares package.
Group: Default
Requires: pycares-python3 = %{version}-%{release}

%description python
python components for the pycares package.


%package python3
Summary: python3 components for the pycares package.
Group: Default
Requires: python3-core
Provides: pypi(pycares)
Requires: pypi(cffi)

%description python3
python3 components for the pycares package.


%prep
%setup -q -n pycares-4.1.2
cd %{_builddir}/pycares-4.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1634582606
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pycares
cp %{_builddir}/pycares-4.1.2/LICENSE %{buildroot}/usr/share/package-licenses/pycares/c4de206e0fa6c5d904eb6c7695f6ffb5d2d90a6b
cp %{_builddir}/pycares-4.1.2/deps/c-ares/LICENSE.md %{buildroot}/usr/share/package-licenses/pycares/e9c597f9b6cf935773ee731d4170b0c2ba142dbb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pycares/c4de206e0fa6c5d904eb6c7695f6ffb5d2d90a6b
/usr/share/package-licenses/pycares/e9c597f9b6cf935773ee731d4170b0c2ba142dbb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
